


select ED1.ID
FROM ECOLI_DATA ED1
left join ECOLI_DATA ED2 on ED1.PARENT_ID = ED2.ID
left join ECOLI_DATA ED3 on ED2.PARENT_ID = ED3.ID
where ED3.PARENT_ID IS NULL and ED3.ID IS NOT NULL
order by ED1.ID


