select SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
from (

select DATE_FORMAT(SALES_DATE,'%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
from ONLINE_SALE
where YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 03

union

select DATE_FORMAT(SALES_DATE,'%Y-%m-%d') as SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
from OFFLINE_SALE
where YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 03
) as T
order by SALES_DATE, PRODUCT_ID, USER_ID
