


select ID,
    case
        WHEN NTILE(4) OVER (order by SIZE_OF_COLONY DESC) = 1 THEN 'CRITICAL'
        WHEN NTILE(4) OVER (order by SIZE_OF_COLONY DESC) = 2 THEN 'HIGH'
        WHEN NTILE(4) OVER (order by SIZE_OF_COLONY DESC) = 3 THEN 'MEDIUM'
        WHEN NTILE(4) OVER (order by SIZE_OF_COLONY DESC) = 4 THEN 'LOW'
    END AS COLONY_NAME
from ECOLI_DATA
order by ID 