select RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE),2) as SCORE
from REST_INFO RI
join REST_REVIEW RR on RR.REST_ID = RI.REST_ID
where RI.ADDRESS like '서울%'
group by 
    RI.REST_ID
order by SCORE desc, RI.FAVORITES desc

# SELECT
#     I.REST_ID,
#     I.REST_NAME,
#     I.FOOD_TYPE,
#     I.FAVORITES,
#     I.ADDRESS,
#     ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
# FROM REST_INFO I
# JOIN REST_REVIEW R
#     ON I.REST_ID = R.REST_ID
# WHERE I.ADDRESS LIKE '서울%'
# GROUP BY
#     I.REST_ID,
#     I.REST_NAME,
#     I.FOOD_TYPE,
#     I.FAVORITES,
#     I.ADDRESS
# ORDER BY
#     SCORE DESC,
#     I.FAVORITES DESC;