-- 코드를 입력하세요

SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, GENDER, count(DISTINCT S.USER_ID) as USERS
from ONLINE_SALE S
join USER_INFO U on S.USER_ID = U.USER_ID
group by YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
HAVING GENDER >= 0
order by 1,2,3


