-- 코드를 작성해주세요
select 
    CONCAT(QUARTER(DIFFERENTIATION_DATE),'Q') as QUARTER,
    count(*) as ECOLI_COUNT
from ECOLI_DATA
group by CONCAT(QUARTER(DIFFERENTIATION_DATE),'Q')
order by CONCAT(QUARTER(DIFFERENTIATION_DATE),'Q')