-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, PRICE * sum(O.AMOUNT) as TOTAL_SALES
from FOOD_ORDER O
join FOOD_PRODUCT P on O.PRODUCT_ID = P.PRODUCT_ID
where O.PRODUCE_DATE >= '2022-05-01' and O.PRODUCE_DATE < '2022-06-01'
group by P.PRODUCT_NAME
order by 3 desc, 1