# -- 코드를 입력하세요
# SELECT 
# *
# from CAR_RENTAL_COMPANY_RENTAL_HISTORY R
# join CAR_RENTAL_COMPANY_CAR C on R.CAR_ID = C.CAR_ID
# join CAR_RENTAL_COMPANY_DISCOUNT_PLAN D on D.CAR_TYPE = C.CAR_TYPE
# AND D.DURATION_TYPE = CASE
#      WHEN DATEDIFF(R.END_DATE, R.START_DATE) + 1 >= REGEXP_SUBSTR(D.duration_type, '[0-9]+') THEN '90일 이상'
#      WHEN DATEDIFF(R.END_DATE, R.START_DATE) + 1 >= 30 THEN '30일 이상'
#      WHEN DATEDIFF(R.END_DATE, R.START_DATE) + 1 >= 7  THEN '7일 이상'
#      ELSE NULL
#  END
# where C.CAR_TYPE = '트럭'
# order by 2 desc, 1 desc

# # select *
# # from CAR_RENTAL_COMPANY_RENTAL_HISTORY R
# # join CAR_RENTAL_COMPANY_CAR C on R.CAR_ID = C.CAR_ID
# # join CAR_RENTAL_COMPANY_DISCOUNT_PLAN D on D.CAR_TYPE = C.CAR_TYPE and REGEXP_SUBSTR(D.duration_type, '[0-9]+') = (DATEDIFF(end_date,start_date)+1)
SELECT
    R.HISTORY_ID,
    FLOOR(
        days * C.DAILY_FEE * (100 - IFNULL(D.DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM (
    SELECT
        HISTORY_ID, CAR_ID,
        (DATEDIFF(END_DATE, START_DATE) + 1) AS days
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) R
JOIN CAR_RENTAL_COMPANY_CAR C
  ON R.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
  ON D.CAR_TYPE = C.CAR_TYPE
 AND CAST(REGEXP_SUBSTR(D.DURATION_TYPE, '[0-9]+') AS UNSIGNED) = (
      SELECT MAX(CAST(REGEXP_SUBSTR(D2.DURATION_TYPE, '[0-9]+') AS UNSIGNED))
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D2
      WHERE D2.CAR_TYPE = C.CAR_TYPE
        AND R.days >= CAST(REGEXP_SUBSTR(D2.DURATION_TYPE, '[0-9]+') AS UNSIGNED)
 )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, R.HISTORY_ID DESC;
