select II.ITEM_ID, II.ITEM_NAME, II.RARITY
from ITEM_TREE IT
join ITEM_INFO II on II.ITEM_ID = IT.ITEM_ID
join ITEM_INFO II2 on II2.ITEM_ID = IT.PARENT_ITEM_ID
where II2.RARITY = 'RARE'
order by II.ITEM_ID desc