select CATEGORY, sum(SALES) as TOTAL_SALES
from BOOK_SALES S
join BOOK B on S.BOOK_ID=B.BOOK_ID
WHERE S.SALES_DATE >= '2022-01-01'
  AND S.SALES_DATE <  '2022-02-01'
group by CATEGORY
order by CATEGORY